name: 'NPM Custom Action'
description: 'Installing and caching NPM packages'
inputs:
  folder-path:  # id of input
    description: 'path to the cache'
    required: true

runs:
  using: "composite"
  steps:
  - name: Cache NPM Dependencies
    uses: actions/cache@v3
    with:
      path: ${{inputs.folder-path}}
      key: ${{runner.os}}-node-modules-${{ hashFiles('package-lock.json')}}   
  - name: Install dependencies
    run: npm install
    shell: bash